import os                                                                                                                                                                                                                   
import json                                                                                                                                                                                                                 
from flask import Flask, send_file, render_template, request                                                                                                                                                                
from reportlab.lib.pagesizes import letter                                                                                                                                                                                  
from reportlab.lib import colors                                                                                                                                                                                            
from reportlab.lib.styles import getSampleStyleSheet                                                                                                                                                                        
from reportlab.lib.units import inch                                                                                                                                                                                        
from reportlab.pdfgen import canvas                                                                                                                                                                                         
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image                                                                                                                                                  
import matplotlib.pyplot as plt                                                                                                                                                                                             
import io                                                                                                                                                                                                                   
                                                                                                                                                                                                                        
app = Flask(__name__)                                                                                                                                                                                                       
                                                                                                                                                                                                                        
# Directorio donde se almacenan las investigaciones                                                                                                                                                                         
INVESTIGATIONS_DIR = '/home/ubuntu/storm/archivos_de_salida/'                                                                                                                                                               
                                                                                                                                                                                                                        
# Función para crear un gráfico de ejemplo                                                                                                                                                                                  
def create_plot():                                                                                                                                                                                                          
     plt.figure()                                                                                                                                                                                                            
     plt.plot([1, 2, 3, 4], [10, 20, 25, 30], color='blue')                                                                                                                                                                  
     plt.title('Ejemplo de Gráfico')                                                                                                                                                                                         
     plt.xlabel('X-axis')                                                                                                                                                                                                    
     plt.ylabel('Y-axis')                                                                                                                                                                                                    
     buf = io.BytesIO()                                                                                                                                                                                                      
     plt.savefig(buf, format='png')                                                                                                                                                                                          
     buf.seek(0)                                                                                                                                                                                                             
     return buf                                                                                                                                                                                                              
                                                                                                                                                                                                                             
# Función para generar el PDF                                                                                                                                                                                               
def generate_pdf(investigation_data):                                                                                                                                                                                       
     buffer = io.BytesIO()                                                                                                                                                                                                   
     doc = SimpleDocTemplate(buffer, pagesize=letter)                                                                                                                                                                        
     styles = getSampleStyleSheet()                                                                                                                                                                                          
     story = []                                                                                                                                                                                                              
                                                                                                                                                                                                                             
     # Título                                                                                                                                                                                                                
     title = Paragraph(investigation_data['title'], styles['Title'])                                                                                                                                                         
     story.append(title)                                                                                                                                                                                                     
     story.append(Spacer(1, 12))                                                                                                                                                                                             
                                                                                                                                                                                                                             
     # Texto de introducción                                                                                                                                                                                                 
     intro = Paragraph(investigation_data['summary'], styles['Normal'])                                                                                                                                                      
     story.append(intro)                                                                                                                                                                                                     
     story.append(Spacer(1, 12))                                                                                                                                                                                             
                                                                                                                                                                                                                             
     # Gráfico de ejemplo                                                                                                                                                                                                    
     plot_buffer = create_plot()                                                                                                                                                                                             
     plot_image = Image(plot_buffer, width=400, height=300)                                                                                                                                                                  
     story.append(plot_image)                                                                                                                                                                                                
     story.append(Spacer(1, 12))                                                                                                                                                                                             
                                                                                                                                                                                                                             
     # Texto adicional                                                                                                                                                                                                       
     additional_text = Paragraph(investigation_data['conclusions'], styles['Normal'])                                                                                                                                        
     story.append(additional_text)                                                                                                                                                                                           
     story.append(Spacer(1, 12))                                                                                                                                                                                             
                                                                                                                                                                                                                             
     # Dibujo de ejemplo (puedes agregar más dibujos si lo deseas)                                                                                                                                                           
     c = canvas.Canvas(buffer, pagesize=letter)                                                                                                                                                                              
     c.setStrokeColorRGB(0.2, 0.5, 0.3)                                                                                                                                                                                      
     c.setFillColorRGB(0.2, 0.5, 0.3)                                                                                                                                                                                        
     c.rect(inch, inch, 6*inch, 9*inch, fill=1)                                                                                                                                                                              
     c.showPage()                                                                                                                                                                                                            
     c.save()                                                                                                                                                                                                                
                                                                                                                                                                                                                             
     # Construir el PDF                                                                                                                                                                                                      
     doc.build(story)                                                                                                                                                                                                        
     buffer.seek(0)                                                                                                                                                                                                          
     return buffer                                                                                                                                                                                                           
                                                                                                                                                                                                                             
# Ruta para la página principal                                                                                                                                                                                             
@app.route('/')                                                                                                                                                                                                             
def index():                                                                                                                                                                                                                
     investigations = [f for f in os.listdir(INVESTIGATIONS_DIR) if os.path.isfile(os.path.join(INVESTIGATIONS_DIR, f))]                                                                                                     
     return render_template('index.html', investigations=investigations)                                                                                                                                                     
                                                                                                                                                                                                                             
# Ruta para generar y descargar el PDF                                                                                                                                                                                      
@app.route('/generate_pdf/<investigation_name>', methods=['POST'])                                                                                                                                                          
def download_pdf(investigation_name):                                                                                                                                                                                       
     investigation_path = os.path.join(INVESTIGATIONS_DIR, investigation_name)                                                                                                                                               
     if os.path.isfile(investigation_path):                                                                                                                                                                                  
          with open(investigation_path, 'r') as file:                                                                                                                                                                         
               investigation_data = json.load(file)                                                                                                                                                                            
          pdf_buffer = generate_pdf(investigation_data)                                                                                                                                                                       
          return send_file(pdf_buffer, as_attachment=True, download_name=f'{investigation_name}.pdf', mimetype='application/pdf')                                                                                             
     else:                                                                                                                                                                                                                   
          return "Archivo no encontrado", 404                                                                                                                                                                                 
                                                                                                                                                                                                                             
if __name__ == '__main__':                                                                                                                                                                                                  
     app.run(host='0.0.0.0', port=5000, debug=True)
